Add columns and kwargs
abstra-app/hackerforms-lib pull request #45
Opened 2022-06-09 15:10 UTC by NirvaleO

Vai adicionar columns aos widgets e em pages e transforma tudo em kwargs.
É breaking change, preciso testar antes pra ver se funciona, mas acho que ta tudo certo

2022-06-09 16:48 UTC, felipereyel commented on hackerforms/input_types.py
> +        self.message = kwargs.get('message')
message vai ser nullable?

2022-06-09 16:48 UTC, felipereyel commented on hackerforms/input_types.py
> +        self.message = kwargs.get('message')
se quer jogar erro nao usa o .get

2022-06-09 16:50 UTC, felipereyel commented on hackerforms/input_types.py
> +        self.message = kwargs.get('message')
vale pros outros inputs tbm

2022-06-09 16:51 UTC, felipereyel commented on hackerforms/input_types.py
> +        self.options = kwargs.get('options')
same para esse

2022-06-09 16:52 UTC, felipereyel commented on hackerforms/input_types.py
> +        self.options = kwargs.get('options')
same

2022-06-09 16:52 UTC, felipereyel commented on hackerforms/input_types.py
> -        self.multiple = multiple
desapareceu com multiple?

2022-06-09 16:53 UTC, felipereyel commented on hackerforms/inputs.py
>      Args:
```suggestion
    Keyword Args:
```

2022-06-09 16:54 UTC, felipereyel commented on hackerforms/inputs.py
>      Args:
vale para baixo tbm

2022-06-09 16:55 UTC, felipereyel commented on hackerforms/output_types.py
> +        self.message = kwargs.get('message', '')
vale pros outros tbm

2022-06-09 16:55 UTC, felipereyel requested changes
Separa columns de kwargs pfvr o PR

2022-06-09 16:57 UTC, felipereyel requested changes
KWARGS vai matar o suggestion de parametros da funcao

toda vez que alguem quiser usar vai ter que ir a documentacao?

![image](https://user-images.githubusercontent.com/26462242/172902652-31430365-83b5-4c55-9ba0-0a9b92c5d86e.png)

nao queremos mais isso?

2022-06-09 18:51 UTC, NirvaleO commented on hackerforms/input_types.py
> +        self.message = kwargs.get('message')
Já eram antes, não?

2022-06-09 18:52 UTC, NirvaleO commented on hackerforms/input_types.py
> -        self.multiple = multiple
oopsssieeeee

2022-06-09 19:07 UTC, felipereyel commented on hackerforms/input_types.py
> +        self.message = kwargs.get('message')
nao pq era obrigado passar o parametro.
agr que eh kwarg nao vai dar erro.
por pelo menos um default ou entao checa

2022-06-09 19:10 UTC, felipereyel commented on hackerforms/page.py
> +    def read(self, message: str, key: str = '', **kwargs):
message ainda vai ser positional param nesse caso? 
ta ficando baguncado

2022-06-09 19:30 UTC, NirvaleO commented on hackerforms/page.py
> +    def read(self, message: str, key: str = '', **kwargs):
a ideia é que tudo seja kwarg, o problema é que a gente precisa de key ou messagem pra passar pra dentro pra inicializar o input

2022-06-10 17:26 UTC, felipereyel approved these changes

2022-06-10 17:29 UTC, felipereyel approved these changes

2022-06-10 17:31 UTC, merged