Add ExecuteJS widget
abstra-app/hackerforms-lib pull request #46
Opened 2022-06-09 20:29 UTC by joaohenrifranco

2022-06-10 18:00 UTC, pedrorv approved these changes

2022-06-10 18:17 UTC, felipereyel requested changes
Documentar context
arquivo sumiu

2022-06-10 18:22 UTC, felipereyel requested changes
Context default e kwargs

2022-06-10 18:58 UTC, felipereyel commented on hackerforms/inputs.py
> +        context (dict): variables to be passed to the JS code
faltou o button text aqui como kwarg, inclusive vc ta usando ele em baixo

2022-06-10 19:07 UTC, felipereyel commented on hackerforms/input_types.py
> +    def __init__(self, code: str, context: dict, key: str):
usar kwargs pfvr

2022-06-13 15:34 UTC, felipereyel approved these changes

2022-06-13 15:43 UTC, merged